version: '3'
services:
  database:
    container_name: postgres
    image: "postgres"
    env_file:
      - database/database.env
    volumes:
      - blog-database-data:/var/lib/postgresql/data/
  dev-env:
    container_name: dev-env
    build:
      context: ./dev-env
    volumes:
      - "..:/workspace"
    stdin_open: true # docker run -i
    tty: true # docker run -t

volumes:
  blog-database-data: null
